{% set name = "grep" %}
{% set version = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://mirrors.kernel.org/gnu/{{ name }}/{{ name }}-{{ version }}.tar.xz
  sha256: 1db2aedde89d0dea42b16d9528f894c8d15dae4e190b59aecc78f5a951276eab

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - make
  host:
    - pcre2

test:
  commands:
    - test -x ${PREFIX}/bin/grep
    - if [ $(which grep) != ${PREFIX}/bin/grep ]; then exit 1; fi
    - grep --version
    - echo hello world | grep hello

about:
  home: https://www.gnu.org/software/grep/
  license: GPL-3.0-or-later
  license_file: COPYING
  summary: |
    Grep searches one or more input files for lines containing a match to a
    specified pattern
  description: |
    Given one or more patterns, grep searches input files for matches to the
    patterns. When it finds a match in a line, it copies the line to standard
    output (by default), or produces whatever other sort of output you have
    requested with options.
  doc_url: https://www.gnu.org/software/grep/manual/

extra:
  recipe-maintainers:
    - calebzulawski
